name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 2.2.7
homepage: https://github.com/danvick/form_builder_file_picker
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  community_material_icon: ^5.9.55
  
  edge_detection:
    git:
      url: https://github.com/Shreemanarjun/edge_detection.git
      ref: master
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.5.0
  image_picker: ^0.8.5+3  
  path: ^1.8.2
  path_provider: ^2.0.12
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
