name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 2.2.7
homepage: https://github.com/danvick/form_builder_file_picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  community_material_icon: ^5.9.55
  document_scanner_flutter: ^0.2.7
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.5.0
  image_picker: ^0.8.5+3  
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
